# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-25 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cogsassignment',
            name='shipment_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ShipmentLine'),
        ),
    ]
