# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-30 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_cogsassignment_unit_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cogsassignment',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
