#!/bin/bash

if [ "True" != "`python -c "import sys; print hasattr(sys, 'real_prefix')"`" ]; then
    echo "ATTENTION!"
    echo "You must use this script whilst inside a virtualenv!"
    echo " "
    exit 1
fi
echo
echo "Dumping out all data"
echo " "
ENVDIR="`python -c \"import os, sys; print os.path.abspath(sys.prefix)\"`"

cd $ENVDIR

echo "Dumping auth fixtures"
python manage.py dumpdata auth.group > ./migration_fixtures/auth_group.json --indent=4
python manage.py dumpdata auth.user > ./migration_fixtures/auth_user.json --indent=4

echo "Dumping basic GL objects"
python manage.py dumpdata gl.company > ./migration_fixtures/gl_company.json --indent=4
python manage.py dumpdata gl.department > ./migration_fixtures/gl_department.json --indent=4
python manage.py dumpdata gl.employee > ./migration_fixtures/gl_employee.json --indent=4
python manage.py dumpdata gl.counterparty > ./migration_fixtures/gl_counterparty.json --indent=4
python manage.py dumpdata gl.account > ./migration_fixtures/gl_account.json --indent=4
python manage.py dumpdata gl.externalaccount > ./migration_fixtures/gl_externalaccts.json --indent=4


echo "Dumping environment"
python manage.py dumpdata environment > ./migration_fixtures/environment.json --indent=4
python manage.py dumpdata reporting > ./migration_fixtures/reporting.json --indent=4

echo "Dumping cashflows"
python manage.py dumpdata base.cashflow > ./migration_fixtures/cashflow.json --indent=4

echo "Dumping expenses"
python manage.py dumpdata base.expense > ./migration_fixtures/expense.json --indent=4

echo "Dumping audit"
python manage.py dumpdata audit > ./migration_fixtures/audit.json --indent=4

echo "Dumping nominal transactions"
python manage.py dumpdata base.nominaltransaction > ./migration_fixtures/nominal.json --indent=4