# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-25 21:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='inventoryitem',
            table='products_inventoryitem',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products_product',
        ),
        migrations.AlterModelTable(
            name='productline',
            table='products_productline',
        ),
        migrations.AlterModelTable(
            name='skuunit',
            table='products_skuunit',
        ),
    ]
