# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-03 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProceedsAdjustment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date', models.DateField()),
                ('adjust_type', models.CharField(blank=True, choices=[(b'CHANNEL_FEES', b'Channel Fees'), (b'GIFTWRAP_FEES', b'Giftwrap'), (b'DISCOUNT', b'Discount'), (b'SHIPPING_CHARGE', b'Shipping Charge')], max_length=20, null=True)),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proceedsadjustment_sale', to='sales.Sale')),
            ],
            options={
                'db_table': 'sales_proceedsadjustment',
            },
        ),
        migrations.RemoveField(
            model_name='channelpayouts',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='channelpayouts',
            name='paid_thru',
        ),
        migrations.RemoveField(
            model_name='channelpayouts',
            name='sales',
        ),
        migrations.AddField(
            model_name='salestax',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unitsale',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ChannelPayouts',
        ),
    ]
