# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-13 14:41
from __future__ import unicode_literals

import accountifie.toolkit.utils.gl_helpers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gl', '0002_transaction_bmo_id'),
        ('sales', '0004_auto_20170406_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='company',
            field=models.ForeignKey(default=accountifie.toolkit.utils.gl_helpers.get_default_company, on_delete=django.db.models.deletion.CASCADE, to='gl.Company'),
        ),
    ]
