# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-27 23:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulfill', '0002_auto_20170325_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fulfillupdate',
            name='fulfillment',
        ),
        migrations.RemoveField(
            model_name='fulfillupdate',
            name='shipper',
        ),
        migrations.DeleteModel(
            name='FulfillUpdate',
        ),
    ]
