# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-14 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfill', '0006_shippingcharge_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingcharge',
            name='packing_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
