# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-16 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfill', '0007_shippingcharge_packing_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulfillline',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
