# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-25 21:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulfill', '0008_auto_20161216_1004'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='batchrequest',
            table='fulfill_batchrequest',
        ),
        migrations.AlterModelTable(
            name='fulfillline',
            table='fulfill_fulfillline',
        ),
        migrations.AlterModelTable(
            name='fulfillment',
            table='fulfill_fulfillment',
        ),
        migrations.AlterModelTable(
            name='fulfillupdate',
            table='fulfill_fulfillupdate',
        ),
        migrations.AlterModelTable(
            name='shippingcharge',
            table='fulfill_shippingcharge',
        ),
        migrations.AlterModelTable(
            name='warehousefulfill',
            table='fulfill_warehousefulfill',
        ),
        migrations.AlterModelTable(
            name='warehousefulfillline',
            table='fulfill_warehousefulfillline',
        ),
    ]
