# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-25 23:04
from __future__ import unicode_literals

import accountifie.gl.bmo
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField()),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fulfill_batchrequest',
            },
        ),
        migrations.CreateModel(
            name='FulfillLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'fulfill_fulfillline',
            },
        ),
        migrations.CreateModel(
            name='Fulfillment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField()),
                ('bill_to', models.CharField(blank=True, max_length=100, null=True)),
                ('use_pdf', models.BooleanField(default=False)),
                ('packing_type', models.CharField(choices=[(b'box', b'box'), (b'pouch', b'pouch')], default=b'box', max_length=30)),
                ('status', models.CharField(choices=[(b'back-ordered', b'back-ordered'), (b'requested', b'requested'), (b'partial', b'partial'), (b'mismatched', b'mismatched'), (b'completed', b'completed')], max_length=20)),
            ],
            options={
                'db_table': 'fulfill_fulfillment',
            },
        ),
        migrations.CreateModel(
            name='FulfillUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateField()),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[(b'back-ordered', b'back-ordered'), (b'requested', b'requested'), (b'partial', b'partial'), (b'mismatched', b'mismatched'), (b'completed', b'completed')], max_length=30)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'fulfill_fulfillupdate',
            },
        ),
        migrations.CreateModel(
            name='ShippingCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(blank=True, max_length=25, null=True)),
                ('external_id', models.CharField(blank=True, max_length=50, null=True)),
                ('packing_id', models.CharField(blank=True, max_length=50, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=25, null=True)),
                ('ship_date', models.DateField()),
                ('charge', models.DecimalField(decimal_places=2, max_digits=8)),
                ('order_related', models.BooleanField(default=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fulfill_shippingcharge',
            },
            bases=(models.Model, accountifie.gl.bmo.BusinessModelObject),
        ),
        migrations.CreateModel(
            name='WarehouseFulfill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_pack_id', models.CharField(blank=True, max_length=100, null=True)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('request_date', models.DateField(blank=True, null=True)),
                ('ship_date', models.DateField(blank=True, null=True)),
                ('shipping_name', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_attn', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_address1', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_address2', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_address3', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_city', models.CharField(blank=True, max_length=50, null=True)),
                ('shipping_zip', models.CharField(blank=True, max_length=20, null=True)),
                ('shipping_province', models.CharField(blank=True, max_length=30, null=True)),
                ('shipping_country', models.CharField(blank=True, max_length=30, null=True)),
                ('shipping_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('shipping_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('handling_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ship_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('fulfillment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehousefulfill', to='fulfill.Fulfillment')),
            ],
            options={
                'db_table': 'fulfill_warehousefulfill',
            },
        ),
        migrations.CreateModel(
            name='WarehouseFulfillLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.InventoryItem')),
                ('warehouse_fulfill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfill_lines', to='fulfill.WarehouseFulfill')),
            ],
            options={
                'db_table': 'fulfill_warehousefulfillline',
            },
        ),
    ]
