# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-25 23:04
from __future__ import unicode_literals

import accountifie.gl.bmo
import accountifie.toolkit.utils.gl_helpers
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('gl', '0002_transaction_bmo_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gl.Counterparty')),
            ],
            options={
                'db_table': 'sales_channel',
            },
        ),
        migrations.CreateModel(
            name='ChannelPayouts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payout_date', models.DateField()),
                ('payout', models.DecimalField(decimal_places=2, max_digits=8)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Channel')),
                ('paid_thru', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payout_paid_thru', to='gl.Counterparty')),
            ],
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payout_date', models.DateField()),
                ('payout', models.DecimalField(decimal_places=2, max_digits=8)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Channel')),
                ('paid_thru', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ch_payout_paid_thru', to='gl.Counterparty')),
            ],
            options={
                'db_table': 'sales_payout',
            },
        ),
        migrations.CreateModel(
            name='PayoutLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tag', models.CharField(blank=True, choices=[(b'STANDALONE', b'Standalone'), (b'REFUND', b'Refund')], max_length=20, null=True)),
                ('payout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_line', to='sales.Payout')),
            ],
            options={
                'db_table': 'sales_payoutline',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField()),
                ('external_channel_id', models.CharField(blank=True, help_text=b'If no ID, leave blank for system-generated ID', max_length=50, null=True, unique=True)),
                ('external_routing_id', models.CharField(blank=True, max_length=50, null=True)),
                ('special_sale', models.CharField(blank=True, choices=[(b'press', b'Press Sample'), (b'consignment', b'Consignment'), (b'prize', b'Gift/Prize'), (b'retailer', b'Retailer Sample'), (b'payment', b'Payment')], max_length=20, null=True)),
                ('is_return', models.BooleanField(default=False)),
                ('shipping_charge', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=11)),
                ('channel_charges', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=11)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('discount_code', models.CharField(blank=True, max_length=50, null=True)),
                ('notification_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('memo', models.TextField(blank=True, null=True)),
                ('gift_wrapping', models.BooleanField(default=False)),
                ('gift_wrap_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('gift_message', models.TextField(blank=True, null=True)),
                ('shipping_name', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_company', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_address1', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_address2', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_city', models.CharField(blank=True, max_length=50, null=True)),
                ('shipping_zip', models.CharField(blank=True, max_length=20, null=True)),
                ('shipping_province', models.CharField(blank=True, max_length=30, null=True)),
                ('shipping_country', models.CharField(blank=True, max_length=30, null=True)),
                ('shipping_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.Channel')),
                ('company', models.ForeignKey(default=accountifie.toolkit.utils.gl_helpers.get_default_company, on_delete=django.db.models.deletion.CASCADE, to='gl.Company')),
                ('customer_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gl.Counterparty')),
                ('paid_thru', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paid_thru', to='gl.Counterparty')),
            ],
            options={
                'db_table': 'sales_sale',
            },
            bases=(models.Model, accountifie.gl.bmo.BusinessModelObject),
        ),
        migrations.CreateModel(
            name='SalesTax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax', models.DecimalField(decimal_places=2, max_digits=11)),
            ],
            options={
                'db_table': 'sales_salestax',
            },
        ),
        migrations.CreateModel(
            name='TaxCollector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sales_taxcollector',
            },
        ),
        migrations.CreateModel(
            name='UnitSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('tag', models.CharField(blank=True, choices=[(b'RETURN', b'Return'), (b'REPLACEMENT', b'Replacement'), (b'PAYMENT', b'Payment')], max_length=20, null=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_sale', to='sales.Sale')),
                ('sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
            options={
                'db_table': 'sales_unitsale',
            },
        ),
        migrations.AddField(
            model_name='salestax',
            name='collector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.TaxCollector'),
        ),
        migrations.AddField(
            model_name='salestax',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_tax', to='sales.Sale'),
        ),
        migrations.AddField(
            model_name='payoutline',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payoutline_sale', to='sales.Sale'),
        ),
        migrations.AddField(
            model_name='channelpayouts',
            name='sales',
            field=models.ManyToManyField(blank=True, to='sales.Sale'),
        ),
    ]
