# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-07 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20170403_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='discount_code',
        ),
        migrations.AlterField(
            model_name='proceedsadjustment',
            name='adjust_type',
            field=models.CharField(blank=True, choices=[(b'CHANNEL_FEES', b'Channel Fees'), (b'GIFTWRAP_FEES', b'Giftwrap'), (b'DISCOUNT', b'Discount'), (b'SHIPPING_CHARGE', b'Shipping Charge'), (b'GIFTCARD_REDEMPTION', b'Giftcard redemption')], max_length=20, null=True),
        ),
    ]
