# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-07 02:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20170406_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='channel_charges',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='is_return',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='shipping_charge',
        ),
    ]
