# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-29 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_payout_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='checkout_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
