# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-16 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_channelpayouts_paid_thru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitsale',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
