# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-14 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_auto_20161216_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitsale',
            name='tag',
            field=models.CharField(blank=True, choices=[(b'RETURN', b'Return')], max_length=20, null=True),
        ),
    ]
