# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-31 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_unitsale_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsale',
            name='special_sale',
            field=models.CharField(blank=True, choices=[(b'press', b'Press Sample'), (b'consignment', b'Consignment'), (b'prize', b'Gift/Prize'), (b'retailer', b'Retailer Sample'), (b'payment', b'Payment')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='special_sale',
            field=models.CharField(blank=True, choices=[(b'press', b'Press Sample'), (b'consignment', b'Consignment'), (b'prize', b'Gift/Prize'), (b'retailer', b'Retailer Sample'), (b'payment', b'Payment')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='unitsale',
            name='tag',
            field=models.CharField(blank=True, choices=[(b'RETURN', b'Return'), (b'REPLACEMENT', b'Replacement')], max_length=20, null=True),
        ),
    ]
