# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-01 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gl', '0002_transaction_bmo_id'),
        ('sales', '0012_auto_20170131_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payout_date', models.DateField()),
                ('payout', models.DecimalField(decimal_places=2, max_digits=8)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Channel')),
                ('paid_thru', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ch_payout_paid_thru', to='gl.Counterparty')),
            ],
        ),
        migrations.CreateModel(
            name='PayoutLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tag', models.CharField(blank=True, choices=[(b'STANDALONE', b'Standalone'), (b'REFUND', b'Refund')], max_length=20, null=True)),
                ('payout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_line', to='sales.Payout')),
            ],
            options={
                'db_table': 'sales_payoutline',
            },
        ),
        migrations.AlterField(
            model_name='unitsale',
            name='tag',
            field=models.CharField(blank=True, choices=[(b'RETURN', b'Return'), (b'REPLACEMENT', b'Replacement'), (b'PAYMENT', b'Payment')], max_length=20, null=True),
        ),
    ]
