# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-08 14:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_payoutline_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelpayouts',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='channelpayouts',
            name='paid_thru',
        ),
        migrations.RemoveField(
            model_name='channelpayouts',
            name='sales',
        ),
        migrations.AddField(
            model_name='salestax',
            name='date',
            field=models.DateField(default=datetime.date(1970, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unitsale',
            name='date',
            field=models.DateField(default=datetime.datetime(1970, 1, 1, 0, 0)),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ChannelPayouts',
        ),
    ]
