# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-25 21:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_payoutline_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsale',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='historicalsale',
            name='company',
        ),
        migrations.RemoveField(
            model_name='historicalsale',
            name='customer_code',
        ),
        migrations.RemoveField(
            model_name='historicalsale',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalsale',
            name='paid_thru',
        ),
        migrations.DeleteModel(
            name='HistoricalSale',
        ),
    ]
