export const AUTH_LOGIN_USER_REQUEST = 'AUTH_LOGIN_USER_REQUEST';
export const AUTH_LOGIN_USER_FAILURE = 'AUTH_LOGIN_USER_FAILURE';
export const AUTH_LOGIN_USER_SUCCESS = 'AUTH_LOGIN_USER_SUCCESS';
export const AUTH_LOGOUT_USER = 'AUTH_LOGOUT_USER';
export const RECEIVE_CPARTY_DATA = 'RECEIVE_CPARTY_DATA'
export const FETCH_CPARTY_DATA = 'FETCH_CPARTY_DATA'

export const RECEIVE_INCOMPLETESALE_DATA = 'RECEIVE_INCOMPLETESALE_DATA'
export const FETCH_INCOMPLETESALE_DATA = 'FETCH_INCOMPLETESALE_DATA'

export const SEND_INCOMPLETESALE_UPDATE = 'SEND_INCOMPLETESALE_UPDATE'
export const RECEIVE_INCOMPLETESALE_UPDATE_RESPONSE = 'RECEIVE_INCOMPLETESALE_UPDATE_RESPONSE'
